[package]
name = "calendar_ia"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
log = "0.4.27"


